[frontend]

http_port = 80  
https_port = 443
websocket_port = 3001

[backend]

websocket_port = 3001
client_id = 'ID'
client_secret = 'SECRET'
redirect_uri = 'http://localhost:5173/auth/callback'
scope = '' #Space seperated list of scopes https://developer.spotify.com/documentation/general/guides/authorization/scopes/ 