# Config 

# Please update frontend/types/configTypes.d.ts whenever this changes layout

# Frontend
[frontend]

http_port = 80  
https_port = 443
websocket_port = 3001

[backend]

websocket_port = 3001
client_id = 'ID'
client_secret = 'SECRET'
redirect_uri = 'https://localhost:8888/callback'